project_name: 'SuperGamer'
game_name: 'Slay the Spire'
run_name: 'claude - vector - mcp - test1'
close_explore: False
close_reflexion: False
close_reset: False
is_base: False
use_mcp: True
mcp:
  max_iter: 8

result_path: 'results'
exec_duration: 0.8  # Increase operation wait time to reduce conflicts

teacher_type: 'Random' # Human or AI or Random

brain:
  base_model: 'claude-3-7-sonnet-20250219' # gpt-4o or claude-3-7-sonnet-20250219
  evaluate_model: 'gpt-4o'

  uct_c: 5.0
  uct_threshold: 0.0

# Long-term memory configuration
long_memory:
  sim_threshold: 0.85  # State similarity threshold

# Vector database configuration
vector_memory:
  similarity_threshold: 0.92  # Object similarity threshold for deduplication
  embedding_type: "open_clip"  # Use default embedding to avoid conflicts
  clip_model: "ViT-B/32"     # CLIP model version
  vector_dim: 512            # Vector dimension
  batch_size: 32             # Batch size
  
  # Image preprocessing configuration
  image_preprocessing:
    target_size: [224, 224]   # Target image size
    normalize: true           # Whether to normalize
    
  # Similarity matching configuration
  similarity_matching:
    high_threshold: 0.9       # High similarity threshold (considered same object)
    medium_threshold: 0.7     # Medium similarity threshold (possibly similar)
    low_threshold: 0.5        # Low similarity threshold (not very similar)
    
  # Deduplication strategy configuration
  deduplication:
    enabled: true             # Whether to enable deduplication
    spatial_threshold: 10     # Spatial distance threshold (pixels)
    content_similarity: 0.8   # Content similarity threshold
    
  # Storage optimization configuration
  storage_optimization:
    compress_vectors: false   # Whether to compress vectors
    pca_components: 256       # PCA dimension reduction components
    cache_size: 1000         # Cache size
    
  # Retrieval configuration
  retrieval:
    default_top_k: 10         # Default number of results to return
    max_results: 50           # Maximum number of results
    enable_reranking: true    # Whether to enable reranking

# Detector configuration (integrated with vector database, also supports MCP)
detector:
  type: 'omni'  # Use omni detector
  clip_model: 'ViT-B/32'
  
  omni:
    som_model_path: './weights/icon_detect/model.pt'
    caption_model_name: 'florence2'
    caption_model_path: './weights/icon_caption_florence'
    BOX_TRESHOLD: 0.6
    iou_threshold: 0.4
    text_overlap_threshold: 0.25

# Database path configuration
database:
  sqlite_path: "./data/sql/slay_the_spire.db"           # SQLite database path
  vector_db_path: "./data/vector"        # Chroma vector database path
  backup_enabled: true                                  # Whether to enable backup
  backup_interval: 3600                                 # Backup interval (seconds)

# Logging configuration
logging:
  level: "INFO"
  file: "./logs/vector_mcp_memory.log"
  max_size: "10MB"
  backup_count: 5

# Performance configuration
performance:
  use_gpu: false              # Whether to use GPU
  num_workers: 4             # Number of worker threads
  prefetch_factor: 2         # Prefetch factor
  pin_memory: true           # Whether to pin memory

# Experimental features
experimental:
  multimodal_fusion: false   # Multimodal fusion
  semantic_clustering: false # Semantic clustering
  temporal_tracking: false   # Temporal tracking

# MCP Tools Configuration
mcp_tools:
  # Environment-specific tool configuration
  environment_tools:
    - "query_environment"  # Query current UI environment information
  
  # Skill management tools
  skill_tools:
    - "select_skill"       # Select the best skill from candidates
  
  # Operation execution tools (rich GUI interaction for Slay the Spire)
  operation_tools:
    - "Click"              # Left click at coordinates
    - "RightSingle"        # Right click at coordinates
    - "LeftDouble"         # Double click at coordinates
    - "Type"               # Type text input
    - "Drag"               # Drag from one coordinate to another
    - "Finished"           # Mark task as completed
    
  # Slay the Spire specific tools (card game interactions)
  game_specific_tools:
    - "card_interactions"   # Play cards, target selection
    - "menu_navigation"     # Navigate game menus and screens
    - "combat_actions"      # Combat-specific actions (end turn, potions)
    - "map_navigation"      # Navigate the map between battles
    - "shop_interactions"   # Buy/sell items in shops
    - "campfire_actions"    # Rest, upgrade, smith at campfires
    - "event_choices"       # Make choices in random events
    
  # Tool availability by game phase/mode
  exploration_mode:
    enabled_tools: ["query_environment", "Click", "menu_navigation", "map_navigation"]
  
  combat_mode:
    enabled_tools: ["query_environment", "Click", "Drag", "card_interactions", "combat_actions"]
  
  menu_mode:
    enabled_tools: ["query_environment", "Click", "Type", "menu_navigation", "shop_interactions", "campfire_actions", "event_choices"]
  
  skill_learning_mode:
    enabled_tools: ["query_environment", "select_skill", "Type", "Finished"]
  
  full_mode:
    enabled_tools: "all"  # Use all available tools

eye:
  width: 1280
  height: 720