# Simple Gym Environment Configuration
# This config is specifically designed for Gym environments without complex dependencies

# Project Information
project_name: "BottomUpAgent-Gym"
game_name: "CartPole-v1"  # Can be changed to any Gym environment
run_name: "gym_test_run"

# Paths
result_path: "results"
log_path: "logs"

# Gym Environment Settings
gym:
  env_id: "CartPole-v1"  # Gym environment ID
  render_mode: "human"    # "human", "rgb_array", or null
  max_episode_steps: 500
  reward_threshold: 195.0
  interactive_mode: false  # Enable interactive user control mode
  gui_enabled: true        # Enable GUI window for visualization
  
# Agent Settings
agent:
  type: "gym_agent"
  exploration_rate: 0.1
  learning_rate: 0.001
  discount_factor: 0.99
  
# Training Settings
training:
  episodes: 1000
  max_steps_per_episode: 500
  save_frequency: 100
  eval_frequency: 50
  
# Logging
logging:
  level: "INFO"
  console: true
  file: true
  
# Visualization (optional)
visualization:
  enabled: false  # Set to true if you want web visualization
  port: 8080
  
# Environment-specific configs
environments:
  "CartPole-v1":
    action_space: "discrete"
    observation_space: "box"
    action_dim: 2
    state_dim: 4
    
  "LunarLander-v2":
    action_space: "discrete"
    observation_space: "box"
    action_dim: 4
    state_dim: 8
    
  "MountainCar-v0":
    action_space: "discrete"
    observation_space: "box"
    action_dim: 3
    state_dim: 2
    
  "Breakout-v4":
    action_space: "discrete"
    observation_space: "box"
    action_dim: 4
    state_dim: [210, 160, 3]  # Image dimensions