project_name: 'SimpleGUITest'
game_name: 'CartPole-v1'
run_name: 'gui-test'
close_explore: True
close_reflexion: True
close_reset: True
is_base: True
use_mcp: False

result_path: 'results'
exec_duration: 1.0

teacher_type: 'Simple'

# Minimal brain configuration
brain:
  base_model: 'simple'  # Use simple random policy
  evaluate_model: 'simple'
  uct_c: 1.0
  uct_threshold: 0.0

# Simple Gym Environment Configuration
gym:
  env_type: "gymnasium"     # Use standard gymnasium
  env_id: "CartPole-v1"     # Simple environment
  render_mode: "rgb_array"   # For GUI display
  max_episode_steps: 500    # Short episodes
  
  # Action and observation spaces (CartPole)
  action_space:
    type: "Discrete"
    n: 2  # Left or Right
    
  observation_space:
    type: "Box"
    shape: [4]  # Cart position, velocity, pole angle, pole velocity
    dtype: "float32"
    low: -4.8
    high: 4.8

# Disable heavy components
hand:
  disable_som: True
  disable_yolo: True
  
eye:
  disable_omniparser: True
  
vector_memory:
  disable_clip: True
  
long_memory:
  disable_wandb: True
